-- V1__create_initial_schema.sql
-- Migración inicial para el esquema del Foro Hub (actualizada según entidades JPA)

-- Tabla de Perfil (debe crearse primero por las FK)
CREATE TABLE perfil (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- Tabla de Curso
CREATE TABLE curso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(100)
);

-- Tabla de Usuario
CREATE TABLE usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo_electronico VARCHAR(150) NOT NULL UNIQUE,
    contrasena TEXT NOT NULL,
    perfiles INTEGER REFERENCES perfil(id)
);

-- Tabla de Topico
CREATE TABLE topico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP(6),
    status VARCHAR(50),
    autor INTEGER REFERENCES usuario(id),
    curso INTEGER REFERENCES curso(id)
);

-- Tabla de Respuesta
CREATE TABLE respuesta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP(6),
    solucion BOOLEAN DEFAULT FALSE,
    autor INTEGER REFERENCES usuario(id),
    topico INTEGER REFERENCES topico(id)
);

-- Insertar perfiles por defecto
INSERT INTO perfil (nombre) VALUES ('ADMIN'), ('USER');

-- Crear índices para mejorar performance
CREATE INDEX idx_topico_autor ON topico(autor);
CREATE INDEX idx_topico_curso ON topico(curso);
CREATE INDEX idx_topico_fecha ON topico(fecha_creacion);
CREATE INDEX idx_respuesta_topico ON respuesta(topico);
CREATE INDEX idx_respuesta_autor ON respuesta(autor);
CREATE INDEX idx_usuario_correo ON usuario(correo_electronico);
